name: pre-commit

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install Poetry
        uses: Gr1N/setup-poetry@v7
      - name: Install Dependencies
        run: poetry install --extras docs -vv
      - uses: pre-commit/action@v2.0.3
